spring.application.name=delivery-fee

spring.datasource.url=jdbc:h2:mem:deliverydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

weather.import.cron=0 15 * * * *
weather.import.url=https://www.ilmateenistus.ee/ilma_andmed/xml/observations.php
server.port=8081
springdoc.swagger-ui.server.url=http://localhost:8081